stages:
  - build
  - build_push_dev
  - deploy_dev
  - build_push_prod
  - deploy_prod

# On branches except master: verify that build works, do not push to registry
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build --pull ./
  except:
    - master

build_dev:
  stage: build_dev
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:dev" ./
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

deploy_dev:
  stage: deploy_dev
  image: amiveth/service-update-helper
  script:
    - export CI_DEPLOY_SERVICE="$CI_DEPLOY_SERVICE_DEV"
    - /update.py
  only:
    - master

build_prod:
  stage: build_prod
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" ./
    - docker push "$CI_REGISTRY_IMAGE:latest"
  when: manual
  only:
    - master

deploy_prod:
  stage: deploy_prod
  image: amiveth/service-update-helper
  script:
    - export CI_DEPLOY_SERVICE="$CI_DEPLOY_SERVICE_PROD"
    - /update.py
  only:
    - master
