stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build --pull ./
  only:
    - branches
  except:
    - master

build_push:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" ./
    - docker push "$CI_REGISTRY_IMAGE"
  environment:
    name: production
    url: https://beerlog.amiv.ethz.ch
  only:
    - master

deploy:
  stage: deploy
  image: amiveth/service-update-helper
  script:
    - /update.py
  only:
    - master
