"""Initial database schema

Revision ID: 6f494f9a37b6
Revises: 
Create Date: 2019-01-30 22:26:15.294337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f494f9a37b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apikeys',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('product_reports',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=128), nullable=False),
    sa.Column('organisation', sa.Enum('AMIV', 'VIS', 'VMP', name='organisationenum'), nullable=False),
    sa.Column('product', sa.Enum('BEER', 'COFFEE', name='productenum'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('apikey_permissions',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('apikey_id', sa.Integer(), nullable=False),
    sa.Column('product', sa.Enum('BEER', 'COFFEE', name='productenum'), nullable=False),
    sa.ForeignKeyConstraint(['apikey_id'], ['apikeys._id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apikey_permissions')
    op.drop_table('product_reports')
    op.drop_table('apikeys')
    # ### end Alembic commands ###
